image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  SLN_PROJECT: "FutebolAmador.sln"

stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .nuget/packages/

before_script:
  - echo "A restaurar pacotes NuGet..."
  - dotnet restore $SLN_PROJECT

build-job:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "Build do projeto..."
    - dotnet build $SLN_PROJECT --configuration Release --no-restore
  artifacts:
    paths:
      - '**/bin/Release'
    expire_in: 1 week
    
unit-test-job:
  stage: test
  dependencies:
    - build-job
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    TEST_PROJECT_PATH: "Tests/Tests.csproj"
  script:
    - echo "Running unit tests"
    - dotnet test $TEST_PROJECT_PATH --no-build --logger "junit;LogFileName=test-results.xml"
  artifacts:
    when: always
    reports:
      junit: "Tests/test-results.xml"
