// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AmateurFootballContext))]
    partial class AmateurFootballContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("Domain.Entities.CancelledMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("IdMatch")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeCancellation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdMatch");

                    b.HasIndex("IdTeam");

                    b.ToTable("CancelledMatch");
                });

            modelBuilder.Entity("Domain.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("Domain.Entities.MatchInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPitch")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdReceiver")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSender")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdPitch");

                    b.HasIndex("IdReceiver");

                    b.HasIndex("IdSender");

                    b.ToTable("MatchInvite");
                });

            modelBuilder.Entity("Domain.Entities.Matches", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompetive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("idPitch")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("IdChat");

                    b.HasIndex("idPitch");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Domain.Entities.MembershipRequests", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPlayer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InviteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPlayerSender")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdTeam");

                    b.ToTable("MembershipRequests");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("IdUser");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Domain.Entities.Pitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pitch");
                });

            modelBuilder.Entity("Domain.Entities.PostPoneMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMatch")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeamPostPone")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostPoneDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdMatch");

                    b.HasIndex("IdTeamPostPone");

                    b.ToTable("PostPoneMatch");
                });

            modelBuilder.Entity("Domain.Entities.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DrawPoints")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdNextRank")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPreviousRank")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LosePoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PointsToPromotion")
                        .HasColumnType("int");

                    b.Property<int>("WinPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNextRank")
                        .IsUnique()
                        .HasFilter("[IdNextRank] IS NOT NULL");

                    b.HasIndex("IdPreviousRank")
                        .IsUnique()
                        .HasFilter("[IdPreviousRank] IS NOT NULL");

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("Domain.Entities.TeamStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MatchResult")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumGoals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTeam");

                    b.HasIndex("MatchesId");

                    b.ToTable("TeamStatistics");
                });

            modelBuilder.Entity("Domain.Entities.Teams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFoundation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("IdCalendar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPitch")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRank")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCalendar");

                    b.HasIndex("IdPitch");

                    b.HasIndex("IdRank");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.HasBaseType("Domain.Entities.Users");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdTeam")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IsAdminLastChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Domain.Entities.SuperAdmin", b =>
                {
                    b.HasBaseType("Domain.Entities.Users");

                    b.ToTable("SuperAdmin");
                });

            modelBuilder.Entity("Domain.Entities.CancelledMatch", b =>
                {
                    b.HasOne("Domain.Entities.Matches", "Match")
                        .WithMany()
                        .HasForeignKey("IdMatch")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teams", "Team")
                        .WithMany()
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.MatchInvite", b =>
                {
                    b.HasOne("Domain.Entities.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pitch", "Pitch")
                        .WithMany()
                        .HasForeignKey("IdPitch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teams", "Receiver")
                        .WithMany("ReceivedInvites")
                        .HasForeignKey("IdReceiver")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teams", "Sender")
                        .WithMany("SentInvites")
                        .HasForeignKey("IdSender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Pitch");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.Matches", b =>
                {
                    b.HasOne("Domain.Entities.Calendar", null)
                        .WithMany("Matches")
                        .HasForeignKey("CalendarId");

                    b.HasOne("Domain.Entities.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pitch", "Pitch")
                        .WithMany()
                        .HasForeignKey("idPitch")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Pitch");
                });

            modelBuilder.Entity("Domain.Entities.MembershipRequests", b =>
                {
                    b.HasOne("Domain.Entities.Player", "Player")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teams", "Team")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId");

                    b.HasOne("Domain.Entities.Users", "Actor")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Domain.Entities.PostPoneMatch", b =>
                {
                    b.HasOne("Domain.Entities.Matches", "Match")
                        .WithMany()
                        .HasForeignKey("IdMatch")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teams", "Team")
                        .WithMany()
                        .HasForeignKey("IdTeamPostPone")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Rank", b =>
                {
                    b.HasOne("Domain.Entities.Rank", "NextRank")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Rank", "IdNextRank")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Rank", "PreviousRank")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Rank", "IdPreviousRank")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NextRank");

                    b.Navigation("PreviousRank");
                });

            modelBuilder.Entity("Domain.Entities.TeamStatistics", b =>
                {
                    b.HasOne("Domain.Entities.Teams", "Team")
                        .WithMany()
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Matches", "Match")
                        .WithMany("Teams")
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Teams", b =>
                {
                    b.HasOne("Domain.Entities.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("IdCalendar")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pitch", "Pitch")
                        .WithMany()
                        .HasForeignKey("IdPitch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("IdRank")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");

                    b.Navigation("Pitch");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.HasOne("Domain.Entities.Users", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teams", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.SuperAdmin", b =>
                {
                    b.HasOne("Domain.Entities.Users", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.SuperAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Calendar", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Domain.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Matches", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Teams", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("MembershipRequests");

                    b.Navigation("ReceivedInvites");

                    b.Navigation("SentInvites");
                });

            modelBuilder.Entity("Domain.Entities.Player", b =>
                {
                    b.Navigation("MembershipRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
