<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Sdk.Publish">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\NovaPasta1\**" />
    <Compile Remove="Interfaces\Entities\**" />
    <Compile Remove="Properties\PublishProfiles\**" />
    <EmbeddedResource Remove="DTOs\NovaPasta1\**" />
    <EmbeddedResource Remove="Interfaces\Entities\**" />
    <EmbeddedResource Remove="Properties\PublishProfiles\**" />
    <None Remove="DTOs\NovaPasta1\**" />
    <None Remove="Interfaces\Entities\**" />
    <None Remove="Properties\PublishProfiles\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IMembershipRequest.cs" />
    <Compile Remove="Interfaces\Repositories\IUnitOfWork.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
