<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\NovaPasta1\**" />
    <EmbeddedResource Remove="DTOs\NovaPasta1\**" />
    <None Remove="DTOs\NovaPasta1\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Repositories\IUnitOfWork.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
    <PackageReference Include="NUnit" Version="4.2.2" />
  </ItemGroup>

</Project>
